### ISSUE TITLE
conditionals issue

### ISSUE THREAD

**Issue by zboldyga** [RxNT/react-jsonschema-form-pagination#1]
Currently this wrapper would need to be used directly over top of the Mozilla project, and the Conditionals wrapper (react-jsonschema-form-conditionals) would need to be applied over top of this wrapper.

We may be able to make the tools work in both orders, but we may not want to give this flexibility. This thread can serve as a discussion around how to use the two tools together.

**Comment by zboldyga** [comment]
Currently I'm filtering the fields based on their tabID, and only sending down (via props, to the child Form component) the current tab's fields in the property object of the schema.

I didn't apply this pruning to the uiSchema. I can easily prune the uiSchema as well, but if I do this, and if pagination wraps conditionals, some of your rules might point to schema or uiSchema items that do not exist. 

I could also trim your rules. Although, I think if we go down this path of making the wrappers compatible in any applied order we could create a lot of extra complexity in the code...

**Comment by zboldyga** [comment]
my plan is to prune uiSchema to contain only relevant info, just holding off on doing any further cleaning up of this decorator until we're sure this pagination approach is OK.

**Comment by mavarazy** [comment]
I was thinking it should be the other way around and conditionals should be the higher layer component. The problem I see with using conditionals as a second layer:

1. Conditional would only have part of the schema and so it can't apply changes to the other tabs, or changes won't persist. (this might be fine, because changes will be reevaluated on schema change, which will happen during navigation and it should be the default behavior anyway, also conditionals can optimize rules on the basis of current fields in the schema, to prevent extra work)
2. Pagination does not change the original schema, while conditionals do, and one of the main paradigms of React is data goes from upper layer to lower layer, so conditionals would need to communicate schema changes to the component above (I'll add it as a feature to conditionals anyway).

So it might work, but I think the other way around it's easier.

**Comment by zboldyga** [comment]
So we can restrict use to this approach?

```js
import Form from "react-jsonschema-form";
import applyPagination from "react-jsonschema-form-pagination";
import applyRules from "react-jsonschema-form-conditionals";

let FormWithPagination = applyPagination(Form);
let FormWithConditionals = applyRules(FormWithPagination);

export function App() {
  return (
    <FormWithConditionals
      rules={rules}
      tabData={tabData}
      liveValidate={false}
      safeRenderCompletion={true}
      noHtml5Validate={true}
      formData={formData}
      schema={schema}
      uiSchema={uiSchema}
    />
  );
}
```

**Comment by mavarazy** [comment]
This works now, with encounter project used as a reference implementation
